name: ⚡️ Feature request
title: "feat: "
description: Suggest an idea for this project
labels: ["feature", "needs: triage"]

body:
  - type: textarea
    attributes:
      label: Current problem
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Preferred solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative options
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    attributes:
      label:  Before submitting
      description: |
        Please ensure your idea fulfills all of the following requirements.
      options:
      - label: I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
        required: true
      - label: I have attached links to possibly related issues and discussions.
        required: true
  - type: checkboxes
    attributes:
      label: Fastest way to get this feature added
      description: |
        Founding is a great way to get your feature added fast. This make community contributions more likely to happen and discharge the maintainers from the burden of being the only one adding features.
      options:
      - label: I want to get this feature ASAP and [found the issue with Algora](https://console.algora.io/org/gl/bounties/community?fund=Cap-go%2Fcapacitor-inappbrowser) we recommend ($100 to $1000)
        required: false
